# Generated by Django 6.0.5 on 2026-06-01 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barbearia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamento',
            name='client',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
