# Generated by Django 6.0.5 on 2026-07-10 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbearia', '0003_agendamento_cliente_category_duracao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='date',
            field=models.DateField(),
        ),
    ]
