# Generated by Django 6.0.5 on 2026-07-10 04:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbearia', '0004_alter_agendamento_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='horario',
            field=models.TimeField(default=datetime.time(4, 9, 2, 123693)),
        ),
    ]
