# Generated by Django 6.0.5 on 2026-07-10 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbearia', '0005_agendamento_horario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='horario',
            field=models.TimeField(),
        ),
    ]
