# Generated by Django 6.0.5 on 2026-07-10 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbearia', '0006_alter_agendamento_horario'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='fim',
            field=models.TimeField(null=True),
        ),
    ]
